create table account (id int8 generated by default as identity, cep varchar(255), city varchar(255), cpf varchar(255), company_name varchar(255), country varchar(255), creci varchar(255), domain varchar(255), email varchar(255), end_date varchar(255), last_name varchar(255), logo varchar(255), neighborhood varchar(255), number varchar(255), office_name varchar(255), password varchar(255), phone varchar(255), proprietario varchar(255), renovation varchar(255), slug varchar(255), start varchar(255), state varchar(255), status int4, street varchar(255), verification int4, primary key (id));
create table address (id int8 generated by default as identity, zone varchar(255), cep varchar(255), complement varchar(255), district varchar(255), number varchar(255), street varchar(255), account_id int8, city_id int8, property_id int8, primary key (id));
create table city (id int8 generated by default as identity, name varchar(255), state_id int8, primary key (id));
create table features (property_id int8 not null, features int4);
create table image (id int8 generated by default as identity, id_account int8, url TEXT, property_id int8, primary key (id));
create table lead (id int8 generated by default as identity, email varchar(255), instant varchar(255), message varchar(255), name varchar(255), phone varchar(255), property_id int8, account_id int8, primary key (id));
create table opportunity (id int8 generated by default as identity, instant varchar(255), property_id int8, account_id int8, lead_id int8, step_id int8, primary key (id));
create table perfis (tenant_id int8 not null, perfis int4);
create table property (id int8 generated by default as identity, area varchar(255), area_total varchar(255), bath_rooms varchar(255), buildings varchar(255), condominium varchar(255), construction_status varchar(255), description text, financeable varchar(255), floors varchar(255), gated_condominium varchar(255), goal int4, iptu varchar(255), name varchar(255), number_rooms varchar(255), permuta varchar(255), price varchar(255), property_administration_fee varchar(255), publication_type varchar(255), rentalprice varchar(255), status_featured int4, status_property int4, suites varchar(255), type_description varchar(255), type_property int4, unit_floor varchar(255), vacancies varchar(255), account_id int8, primary key (id));
create table state (id int8 generated by default as identity, name varchar(255), account_id int8, primary key (id));
create table step (id int8 generated by default as identity, name varchar(15), account_id int8, primary key (id));
create table tenant (id int8 generated by default as identity, cep varchar(255), city varchar(255), country varchar(255), creci varchar(255), domain varchar(255), email varchar(255), end_date varchar(255), last_name varchar(255), neighborhood varchar(255), number varchar(255), office_name varchar(255), password varchar(255), phone varchar(255), proprietario varchar(255), renovation varchar(255), slug varchar(255), start varchar(255), state varchar(255), status int4, street varchar(255), verification int4, account_id int8, primary key (id));
create table theme (id int8 generated by default as identity, main_color varchar(255), name varchar(255), tenant_id int8, primary key (id));
create table urls (id int8 generated by default as identity, id_account int8, url TEXT, property_id int8, primary key (id));
create table user_admin_perfis (user_admin_id int8 not null, perfis int4);
create table user_admin (id int8 generated by default as identity, creci varchar(255), email varchar(255), end_date varchar(255), last_name varchar(255), password varchar(255), slug varchar(255), start varchar(255), status int4, verification int4, primary key (id));
create table warranties (property_id int8 not null, warranties int4);

-- ASAAS Tables
create table asaas_customers (id int8 generated by default as identity, asaas_customer_id varchar(255) unique not null, account_id int8 not null, name varchar(255) not null, cpf_cnpj varchar(255) not null, email varchar(255), mobile_phone varchar(255), phone varchar(255), postal_code varchar(255), address varchar(255), address_number varchar(255), complement varchar(255), province varchar(255), city varchar(255), state varchar(255), country varchar(255), created_at timestamp, updated_at timestamp, primary key (id));

create table asaas_subscriptions (id int8 generated by default as identity, asaas_subscription_id varchar(255) unique not null, asaas_customer_id int8 not null, billing_type varchar(50) not null, value decimal(10,2) not null, cycle varchar(50) not null, description varchar(255), next_due_date date, status varchar(50), end_date date, max_payments int4, external_reference varchar(255), created_at timestamp, updated_at timestamp, primary key (id));

create table asaas_payments (id int8 generated by default as identity, asaas_payment_id varchar(255) unique not null, asaas_subscription_id int8, asaas_customer_id int8 not null, billing_type varchar(50) not null, value decimal(10,2) not null, status varchar(50), due_date date, payment_date date, description varchar(255), external_reference varchar(255), invoice_url varchar(500), bank_slip_url varchar(500), pix_qr_code text, pix_copy_paste text, created_at timestamp, updated_at timestamp, primary key (id));

alter table if exists tenant add constraint UK_1wuu4ilo8ya2tm94iswtp6ev1 unique (email);
alter table if exists user_admin add constraint UK_owgburtx5te2evtm2sqyu926n unique (email);
alter table if exists address add constraint FKascogpq8x3gfx04oy2fr6l3i5 foreign key (account_id) references account;
alter table if exists address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city;
alter table if exists address add constraint FKcaqh5qfje1gr350yx6yppp1tl foreign key (property_id) references property;
alter table if exists city add constraint FK6p2u50v8fg2y0js6djc6xanit foreign key (state_id) references state;
alter table if exists features add constraint FK1eo9kitce40ane65nddtulrxh foreign key (property_id) references property;
alter table if exists image add constraint FK6oqm8c6mg2dgedoppcbu8sm5q foreign key (property_id) references property;
alter table if exists lead add constraint FK64eaeh91o5wg9qf2fslh6q9jp foreign key (account_id) references account;
alter table if exists opportunity add constraint FK9mvhqgny93la8u8k2gd531nex foreign key (account_id) references account;
alter table if exists opportunity add constraint FKjne12qk02v3txj39pdxg2lm4t foreign key (lead_id) references lead;
alter table if exists opportunity add constraint FKhw48xwingbpa9u39b1wwfpaoh foreign key (step_id) references step;
alter table if exists perfis add constraint FKht3ep9ggca63jgjg4033kq8o7 foreign key (tenant_id) references tenant;
alter table if exists property add constraint FKpmg390ndhtclv25djunt7lpng foreign key (account_id) references account;
alter table if exists state add constraint FKasgdjv4ylyne4v6o7v1g51qkp foreign key (account_id) references account;
alter table if exists step add constraint FKf8vc8x9xb8rnhvje3ldfigpb5 foreign key (account_id) references account;
alter table if exists tenant add constraint FKc6sqtvsm3v1dwuwjah60on9p8 foreign key (account_id) references account;
alter table if exists theme add constraint FKabwqgxf34n9rr749heqwawleg foreign key (tenant_id) references tenant;
alter table if exists urls add constraint FK3id6v5b8pehmfr0ib0h8rf2g7 foreign key (property_id) references property;
alter table if exists user_admin_perfis add constraint FKf9hcelnsh3qbamr9eu7i0930v foreign key (user_admin_id) references user_admin;
alter table if exists warranties add constraint FK1fhf5jayugolwxvy4da29rl2v foreign key (property_id) references property;

-- ASAAS Foreign Keys
alter table if exists asaas_customers add constraint FK_asaas_customers_account foreign key (account_id) references account;
alter table if exists asaas_subscriptions add constraint FK_asaas_subscriptions_customer foreign key (asaas_customer_id) references asaas_customers;
alter table if exists asaas_payments add constraint FK_asaas_payments_customer foreign key (asaas_customer_id) references asaas_customers;
alter table if exists asaas_payments add constraint FK_asaas_payments_subscription foreign key (asaas_subscription_id) references asaas_subscriptions;
