spring.profiles.active=${APP_PROFILE:dev}

spring.jpa.open-in-view=false

#SequenciaDeCaracteresParaAssinarToken
jwt.secret=${JWT_SECRET:vazio}
jwt.expiration=${JWT_EXPIRATION:86400}

server.port=8080

aws.access_key_id=AKIAWLWXGVARTPFZCIWI
aws.secret_access_key= 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
s3.bucket=dynamous
s3.region=sa-east-1

#relacionado oo upload de imagens
img.prefix.tenant.property= tp

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


