#spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.hibernate.hbm2ddl.delimiter=;


spring.datasource.url=jdbc:postgresql://localhost:5432/standidata
spring.datasource.username= postgres
spring.datasource.password= 1234567


#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update

# Vercel Configuration
vercel.token=${VERCEL_TOKEN:pZjVnDjuo2pYz0H51TxiehC1}
vercel.project.id=${VERCEL_PROJECT_ID:prj_AyCATbNZesYrKwjBWOhuQ7spe07z}
vercel.team.id=${VERCEL_TEAM_ID:}


spring.mail.host=smtp.gmail.com
spring.mail.username=dynamousads@gmail.com
spring.mail.password=nzxnruwgssqehapp
spring.mail.smtp.port= 465
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.socketFactory.port = 465
spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback = false
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.ssl.enable = true

# Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY: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}
stripe.success.url=${STRIPE_SUCCESS_URL:http://localhost:3000/payment/success}
stripe.cancel.url=${STRIPE_CANCEL_URL:http://localhost:3000/payment-cancel}

