spring.profiles.active=${APP_PROFILE:test}

spring.jpa.open-in-view=false
#spring.jpa.defer-datasource-initialization=true

spring.main.allow-circular-references=true
default.sender=${EMAIL_SENDER:vazio}
default.recipient=${EMAIL_RECIPIENT:vazio}


#valores para expiração e segredo de segurança
jwt.secret=${JWT_SECRET:vazio} 
jwt.expiration=${JWT_EXPIRATION:8600000000}


#informações aws
#aws.access_key_id=${AWS_KEY:vazio}
#aws.secret_access_key=${AWS_SECRET:vazio}

s3.bucket=dynamous
s3.region=sa-east-1


#relacionado oo upload de imagens
img.prefix.tenant.property= tp

#relacionado oo upload de imagens
img.prefix.tenant.profile= cp
img.profile.size=300

server.port=${PORT:8080}

#spring.mail.host=smtp.gmail.com
#spring.mail.username=dynamousads
#spring.mail.password=oevkxgcdgvvlektu
#spring.mail.properties.mail.smtp.auth = true
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory
#spring.mail.properties.mail.smtp.socketFactory.fallback = false
#spring.mail.properties.mail.smtp.starttls.enable = true
#spring.mail.properties.mail.smtp.ssl.enable = true

spring.mvc.static-path-pattern=/static/**

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



spring:
  servlet: 
    multipart: 
       enabled: true 
     
       max-file-size:       10MB 
       max-request-size:    10MB

server.tomcat.relaxed-query-chars=|,{,},[,],`,^

